### ISSUE TITLE
"ModuleNotFoundError: No module named 'bloodyAD.cli_modules'" in BloodyAD 0.1.9 

### ISSUE THREAD

**Issue by jsdhasfedssad** [CravateRouge/bloodyAD#32] opened 2023-01-08 15:00 UTC
Hi,

I saw your new DNS functionalty and wanted to test that but using BloodyAD 0.1.9 errors for me. I can't even exeute "bloodyAD -h". See below. 

I installed BloodyAD as per your instructions. Is it only me or is something broken?

Thanks!

<img width="440" alt="bloodyad1" src="https://user-images.githubusercontent.com/97032878/211203322-077835a6-4a89-41c8-af6d-a89b199f1c21.png">

**Comment by CravateRouge** [comment] 2023-01-09 11:27
Thank you for telling me, I totally forgot to set the package structure accordingly. Should be solved with 0.2.0.

**Comment by jsdhasfedssad** [comment] 2023-01-09 13:07
Sorry but I get different yet similar error in version 0.2.0.

![bloodyad1](https://user-images.githubusercontent.com/97032878/211314433-ba44379c-916b-4f61-8dda-e7e24e518a95.png)

**Comment by CravateRouge** [comment] 2023-01-09 14:52
How did you install it?

**Comment by jsdhasfedssad** [comment] 2023-01-09 17:11
I copied your release tagged 10, unpacked it then installed it as per your instructions here in a virtual environment.

**Comment by CravateRouge** [comment] 2023-01-09 17:55
Could you detail the commands you did? Something like `tar -xvf` and `pip install v0.2.0/.`? I ask you that because using `pip install bloodyad` works on a clean environment.

**Comment by jsdhasfedssad** [comment] 2023-01-09 19:44
Sure.

I copied your release tagged 10 (zip) then I unpacked it using the GUI of the file manager Thunar (default in Kali). I then did the below (taken from the command history):

<img width="239" alt="bloodyad2" src="https://user-images.githubusercontent.com/97032878/211394134-bbd35fa7-dcad-4643-8611-d59fabb04c5c.png">

**Comment by CravateRouge** [comment] 2023-01-09 21:20
I can't reproduce your bug. Try to just `pip install bloodyAD` on a clean environment. Should work

**Comment by CravateRouge** [comment] 2023-01-13 21:18
You can retry with the new version (v0.2.1), I didn't make packaging changes but who knows! (And don't forget to check you have cli_modules directory under bloodyAD directory)

**Comment by jsdhasfedssad** [comment] 2023-01-16 14:07
I don't know what to belive anymore... For what it is worth, if I clone main and install it in a virtual environment using your instructions, running BloodyAD fails from within the virtual environment but not from outside it after deactivating the virtual environment.

![bloodyad3](https://user-images.githubusercontent.com/97032878/212695521-813dede9-3c65-4aea-a9d4-c7faa436b641.png)

But... if I install release 1.8.0 into a virtual environment and install it using your instructions,  running BloodyAD from within the  virtual environment works...


![bloodyad4](https://user-images.githubusercontent.com/97032878/212696732-8c16eff5-5abb-49e1-9fe5-9ad9d41ee166.png)

**Comment by jsdhasfedssad** [comment] 2023-01-16 15:26
Update. I managed to get main to work from within a virtual environment. One need to execute "pip install six" from within the virtual environment. I can see that that dependency is missing from the file "requirements.txt". 

This also explains why main works from outside the virtual environment, Kali probably has "six" installed by default and why 1.8.9 works since that does not need the dependency "six".

**Comment by CravateRouge** [comment] 2023-01-16 17:24
I forgot to correctly remove this dependency, should be fixed with [d816138](https://github.com/CravateRouge/bloodyAD/commit/d8161382377169da44f8687bf594f5b295a51976) thanks for pointing it out!

**Closed** 2023-01-17 09:39 UTC
